name: geopython-workshop
markdown: kramdown
highlighter: rouge
timezone: GMT
baseurl: https://geopython.github.io/geopython-workshop/
description: Doing Geospatial in Python
keywords: python, geospatial, pycsw, pygeoapi, pygeometa, pygeoapi, OWSLib, fiona, shapely, rasterio
gems:
- jekyll-mentions
- jekyll-sitemap
